### ISSUE TITLE
Review_Pipes

### ISSUE THREAD

**Issue by Jerfin97** [Jerfin97/Turbo_Shell_Conchinha#100]

**Comment by Jerfin97** [comment]
Pipes estao leakando e checar erros

**Comment by Jerfin97** [comment]
No more leaks in pipes

**Comment by Jerfin97** [comment]
Nos Reviews Meu Pensamento era Ir fazendo comentarios com os testes pra ter uma especie de checklist Em cima de cada comando ou bloco de comandos no caso dos builtins;

**Comment by dvargas1** [comment]
Working
Comandos simples
ls -la | grep signal
ls -la | grep signal | wc -l
ls -la | grep signal | wc -l | cat -e | cat -e | cat -e | cat -e | cat | wc -l


Com pipes
<main.c cat | wc -l
<main.c cat | grep signal | wc -l
<main.c cat | grep signal | wc -l > outfile.txt
