### ISSUE TITLE
Erro no Redirect quando arquivos nao existem

### ISSUE THREAD

**Issue by dvargas1** [Jerfin97/Turbo_Shell_Conchinha#149]
![image](https://user-images.githubusercontent.com/21111088/215272977-301abc76-304c-4887-ba40-731c2e27d241.png)
ta printando duas linhas a mais no erro

**Comment by dvargas1** [comment]
![image](https://user-images.githubusercontent.com/21111088/215273055-79789c04-46f1-49e2-9c37-6e68d52147e0.png)
Nos pipes ele ta parando tbm, acho que otimo.

**Comment by Jerfin97** [comment]
Da pra deixar bonito se quiser pos almoco a gente faz isso safe

**Comment by dvargas1** [comment]
Resolvido na Main
