### ISSUE TITLE
Variavel de ambiente direto nao pode retornar erro ?

### ISSUE THREAD

**Issue by dvargas1** [Jerfin97/Turbo_Shell_Conchinha#166]
![image](https://user-images.githubusercontent.com/21111088/215569112-88bd4da0-b2ae-4179-b561-8418e8caefd7.png)

'e valido lidar com isso ?

**Comment by dvargas1** [comment]
![image](https://user-images.githubusercontent.com/21111088/215570634-a8178c94-ba9a-442b-8549-f9847b749913.png)
E se tiver comando depois tem que funcionar. . .

**Comment by Jerfin97** [comment]
Ai e fueda ein

**Comment by Jerfin97** [comment]
Acho que nao vou tratar isso nao deve demorar
