### ISSUE TITLE
Inconsistencia

### ISSUE THREAD

**Issue by dvargas1** [Jerfin97/Turbo_Shell_Conchinha#178]
Quando coloca pra rodar um arquivo sem premissao executavel
voltando 1 e path not found

deveria mostrar erro de impossibilidade de execuçao e voltando 127

**Comment by Jerfin97** [comment]
E so meter um if dentro do erro do access e do access_pipe pra ver se e arquivo e dar um erro diferente

**Comment by Jerfin97** [comment]
Se quiser claro

**Comment by Jerfin97** [comment]
Arquivo sem permissao executavel tem que retornar erro diferente de path not found

**Comment by Jerfin97** [comment]
com valor de 126

**Comment by Jerfin97** [comment]
Fazer um if com access vendo se e  file e se e executavel se nao for executavel e for arquivo dar permission denied
