### ISSUE TITLE
teste exit 999999999999999999999999999999999

### ISSUE THREAD

**Issue by dvargas1** [Jerfin97/Turbo_Shell_Conchinha#183]
ex 12:
bash: ./minishell
Minishell> exit 99999999999999999999 (20 dígitos)
minishel: exit: 99999999999999999999: numeric argument required
bash:

ta aceitando o argumento que nao deveria.

**Comment by Jerfin97** [comment]
![image](https://user-images.githubusercontent.com/70494815/216737426-dc681ab3-9054-4a2e-8a93-a4b017e0890f.png)

**Comment by Jerfin97** [comment]
Feito;
