### ISSUE TITLE
Quotes round 2

### ISSUE THREAD

**Issue by dvargas1** [Jerfin97/Turbo_Shell_Conchinha#45]

**Comment by dvargas1** [comment]
Me parece que o comportamento de retorno agora esta correto, o problema agora e saber quando imprime um tipo de caractere e outro nao.

**Comment by Jerfin97** [comment]
Boa

**Comment by Jerfin97** [comment]
Vou checar os casos das aspas quando voltar pra casa e a gente resolve isso.
