### ISSUE TITLE
Review_Builtins

### ISSUE THREAD

**Issue by Jerfin97** [Jerfin97/Turbo_Shell_Conchinha#51]
Dar uma revisada nos builtins todos e checas os casos de erro.

**Comment by Jerfin97** [comment]
Nos Reviews Meu Pensamento era Ir fazendo comentarios com os testes pra ter uma especie de checklist Em cima de cada comando ou bloco de comandos no caso dos builtins;

**Comment by dvargas1** [comment]
Working no leaks
ECHO
echo ola
echo ola "$PAPERSIZE"
echo ola "'"PAPERSIZE"'"
echo "$"PAPERSIZE

**Comment by dvargas1** [comment]
Working no leaks
CD
cd /usr/bin
cd /usr/bin/1231231231 -- erro com retorno de 1
cd ---- com unset HOME da erro e reotno de 1

**Comment by dvargas1** [comment]
PWD 
![image](https://user-images.githubusercontent.com/21111088/215566275-ea829922-95a6-449f-99c5-e024e4fec42d.png)

Certinho
