### ISSUE TITLE
Verificar esse teste

### ISSUE THREAD

**Issue by dvargas1** [Jerfin97/Turbo_Shell_Conchinha#91]
Encontrar o motivo dos testes no echo nao estarem passando com simbolos e numeros isolados no fim da string.

echo ola =
ou
echo ola 1

da sigabort e coredump

Imagino que venha da split spaces ou da clean, principalmente no fim do while onde eu termino de montar a string, deve estar dando ruim exatamente ali.

**Comment by Jerfin97** [comment]
pode deixar que eu meto essa pra noix

**Comment by Jerfin97** [comment]
Ta dando erro no freeing pq não sei exatamente, mas se eu tiro da leak a rodo se eu deixo da double free já no primeiro pointer de inp->args ;
lexer linha 124 ft_freeing dando crash

**Comment by dvargas1** [comment]
Que merda irmao, sera que ele ta tentando acessar memoria que nao tem nada ? fiz testes aqui mas sem nenhum sucesso que bagulho de doido.

**Comment by Jerfin97** [comment]
Muito estranho to tentando achar o problema, mas não dão em nada os testes

**Comment by Jerfin97** [comment]
O problema ta na split_in_spaces kakdkasdk

**Comment by Jerfin97** [comment]
Agora o que extamente eu nâo sei vou checar

**Comment by dvargas1** [comment]
Maldita hora que eu fui pegar essa task meu deus ! Em 15 de jan. de 2023 17:33, Jefferson Luiz ***@***.***> escreveu:
O problema ta na split_in_spaces kakdkasdk

**Comment by Jerfin97** [comment]
Mas o erro é pequeno ta na linha 70 do parse_input.c
Já sinalizei só meter uma função diferente lá pra contar os espaços.

**Comment by Jerfin97** [comment]
Vou dar um push agr com ela meio que resolvida com fita durex mas resolvida.
