### ISSUE TITLE
Verifica'cao na expansao

### ISSUE THREAD

**Issue by dvargas1** [Jerfin97/Turbo_Shell_Conchinha#95]
![image](https://user-images.githubusercontent.com/21111088/212680719-ff4f99b5-a4ad-4fbc-b005-18f6ea4c5671.png)
Verificar a regra de expansao

**Comment by Jerfin97** [comment]
Procurar pelo "=" no final do nome da variavel caso não exista botar um "vazio" 
Se tiver duas seguidas que não existam ele coloca só um espaço.
